on: push

jobs:
  copycat:
    name: Copy and git clone
    runs-on: ubuntu-latest
    env:
      DIRNAME: mydirectory
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print folder structure
        run: |
          mv * $DIRNAME
      - name: List folder structure
        run: ls
