on: push

jobs:
  copycat:
    name: Copy and git clone
    runs-on: ubuntu-latest
    env:
      DIRNAME: mydirectory
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create subdirectory and move all files and directories (except itself) into it
        run: |
          mkdir $DIRNAME
          ls | grep -v $DIRNAME | xargs mv -t $DIRNAME
      - name: git clone
        run: git clone https://github.com/jsx101/cdk-test.git
      - name: Move folder into cdk app
        run: mv $DIRNAME cdk-test
      - name: CD and LS
        run: cd cdk-test && ls
