on: push

jobs:
  copycat:
    name: Copy and git clone
    runs-on: windows-latest
    steps:
      - name: Create subfolder
        env:
          DIRNAME_PATH: mydirectory
        run: |
          mkdir $DIRNAME_PATH
          cd $DIRNAME_PATH
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print folder structure
        run: ls