on: push

jobs:
  copycat:
    name: Copy and git clone
    runs-on: ubuntu-latest
    env:
      DIRNAME: mydirectory
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print folder structure
        run: |
          mkdir $DIRNAME
          for i in `ls -a | grep -Ev '^(SUBDIR|\.\.?)$'`; do mv $i SUBDIR; done
      - name: List folder structure
        run: ls
