on: push

jobs:
  copycat:
    name: Copy and git clone
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Print folder structure
        env:
          DIRNAME: mydirectory
        run: |
          ls
          echo The directory name is $DIRNAME
